// src/components/Calendar/Calendar.jsx
const Calendar = () => {
    return (<div className="calendar__block">
        <div className="calendar__nav">
            <div className="calendar__month">Сентябрь 2023</div>
            <div className="nav__actions">
                <div className="nav__action" data-action="prev">
                    <svg xmlns="http://www.w3.org/2000/svg" width="6" height="11" viewBox="0 0 6 11">
                        <path d="M5.72945 1.95273C6.09018 1.62041 6.09018 1.0833 5.72945 0.750969C5.36622 0.416344 4.7754 0.416344 4.41218 0.750969L0.528487 4.32883C-0.176162 4.97799 -0.176162 6.02201 0.528487 6.67117L4.41217 10.249C4.7754 10.5837 5.36622 10.5837 5.72945 10.249C6.09018 9.9167 6.09018 9.37959 5.72945 9.04727L1.87897 5.5L5.72945 1.95273Z" />
                    </svg>
                </div>
                <div className="nav__action" data-action="next">
                    <svg xmlns="http://www.w3.org/2000/svg" width="6" height="11" viewBox="0 0 6 11">
                        <path d="M0.27055 9.04727C-0.0901833 9.37959 -0.0901832 9.9167 0.27055 10.249C0.633779 10.5837 1.2246 10.5837 1.58783 10.249L5.47151 6.67117C6.17616 6.02201 6.17616 4.97799 5.47151 4.32883L1.58782 0.75097C1.2246 0.416344 0.633778 0.416344 0.270549 0.75097C-0.0901831 1.0833 -0.090184 1.62041 0.270549 1.95273L4.12103 5.5L0.27055 9.04727Z" />
                    </svg>
                </div>
            </div>
        </div>
        <div className="calendar__content">
            <div className="calendar__days-names">
                <div className="calendar__day-name">пн</div>
                <div className="calendar__day-name">вт</div>
                <div className="calendar__day-name">ср</div>
                <div className="calendar__day-name">чт</div>
                <div className="calendar__day-name">пт</div>
                <div className="calendar__day-name -weekend-">сб</div>
                <div className="calendar__day-name -weekend-">вс</div>
            </div>
            <div className="calendar__cells">
                <div className="calendar__cell _other-month">28</div>
                <div className="calendar__cell _other-month">29</div>
                <div className="calendar__cell _other-month">30</div>
                <div className="calendar__cell _cell-day">31</div>
                <div className="calendar__cell _cell-day">1</div>
                <div className="calendar__cell _cell-day _weekend">2</div>
                <div className="calendar__cell _cell-day _weekend">3</div>
                <div className="calendar__cell _cell-day">4</div>
                <div className="calendar__cell _cell-day">5</div>
                <div className="calendar__cell _cell-day ">6</div>
                <div className="calendar__cell _cell-day">7</div>
                <div className="calendar__cell _cell-day _current">8</div>
                <div className="calendar__cell _cell-day _weekend">9</div>
                <div className="calendar__cell _cell-day _weekend">10</div>
                <div className="calendar__cell _cell-day">11</div>
                <div className="calendar__cell _cell-day">12</div>
                <div className="calendar__cell _cell-day">13</div>
                <div className="calendar__cell _cell-day">14</div>
                <div className="calendar__cell _cell-day">15</div>
                <div className="calendar__cell _cell-day _weekend">16</div>
                <div className="calendar__cell _cell-day _weekend">17</div>
                <div className="calendar__cell _cell-day">18</div>
                <div className="calendar__cell _cell-day">19</div>
                <div className="calendar__cell _cell-day">20</div>
                <div className="calendar__cell _cell-day">21</div>
                <div className="calendar__cell _cell-day">22</div>
                <div className="calendar__cell _cell-day _weekend">23</div>
                <div className="calendar__cell _cell-day _weekend">24</div>
                <div className="calendar__cell _cell-day">25</div>
                <div className="calendar__cell _cell-day">26</div>
                <div className="calendar__cell _cell-day">27</div>
                <div className="calendar__cell _cell-day">28</div>
                <div className="calendar__cell _cell-day">29</div>
                <div className="calendar__cell _cell-day _weekend">30</div>
                <div className="calendar__cell _other-month _weekend">1</div>
            </div>
        </div>

        <input type="hidden" id="datepick_value" value="08.09.2023" />
        <div className="calendar__period">
            <p className="calendar__p date-end">Выберите срок исполнения <span className="date-control"></span>.</p>
        </div>
    </div>);
}

export default Calendar;

// src/components/CalendarComponent.vue
<template>

          <div class="pop-new-card__calendar calendar">
            <p class="calendar__ttl subttl">Даты</p>
            <div class="calendar__block">
              <div class="calendar__nav">
                <div class="calendar__month">{{ currentMonthFormatted }}</div>
                <div class="nav__actions">
                  <div class="nav__action" data-action="prev" @click="prevMonth">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="6"
                      height="11"
                      viewBox="0 0 6 11"
                    >
                      <path
                        d="M5.72945 1.95273C6.09018 1.62041 6.09018 1.0833 5.72945 0.750969C5.36622 0.416344 4.7754 0.416344 4.41218 0.750969L0.528487 4.32883C-0.176162 4.97799 -0.176162 6.02201 0.528487 6.67117L4.41217 10.249C4.7754 10.5837 5.36622 10.5837 5.72945 10.249C6.09018 9.9167 6.09018 9.37959 5.72945 9.04727L1.87897 5.5L5.72945 1.95273Z"
                      />
                    </svg>
                  </div>
                  <div class="nav__action" data-action="next" @click="nextMonth">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="6"
                      height="11"
                      viewBox="0 0 6 11"
                    >
                      <path
                        d="M0.27055 9.04727C-0.0901833 9.37959 -0.0901832 9.9167 0.27055 10.249C0.633779 10.5837 1.2246 10.5837 1.58783 10.249L5.47151 6.67117C6.17616 6.02201 6.17616 4.97799 5.47151 4.32883L1.58782 0.75097C1.2246 0.416344 0.633778 0.416344 0.270549 0.75097C-0.0901831 1.0833 -0.090184 1.62041 0.270549 1.95273L4.12103 5.5L0.27055 9.04727Z"
                      />
                    </svg>
                  </div>
                </div>
              </div>

              <div class="calendar__content">
                <div class="calendar__days-names">
                  <div
                    v-for="day in dayNames"
                    :key="day"
                    class="calendar__day-name"
                  >
                    {{ day }}
                  </div>
                </div>

                <div class="calendar__cells">
                  <div
                    v-for="(day, index) in calendarDays"
                    :key="index"
                    class="calendar__cell"
                    :class="getCellClasses(day)"
                    @click="selectDate(day)"
                  >
                    {{ day.date ? day.date.date() : '' }}
                  </div>
                </div>
              </div>

              <div class="calendar__period">
                <p class="calendar__p date-end">
                  {{ dateLabel }} <span class="date-control">{{ selectedDateFormatted }}</span>
                </p>
              </div>
            </div>
          </div>
</template>

<script setup>
import dayjs from 'dayjs'
import { computed, ref } from 'vue'

dayjs.locale('ru')

const currentMonth = ref(dayjs())
const selectedDate = ref(null)

const dayNames = ['пн', 'вт', 'ср', 'чт', 'пт', 'сб', 'вс']

const calendarDays = computed(() => {
  const start = currentMonth.value.startOf('month').startOf('week')
  const end = currentMonth.value.endOf('month').endOf('week')
  const days = []
  let day = start

  while (day <= end) {
    days.push({
      date: day,
      isCurrentMonth: day.month() === currentMonth.value.month(),
      isToday: day.isSame(dayjs(), 'day'),
      isWeekend: day.day() === 6 || day.day() === 0,
    })
    day = day.add(1, 'day')
  }

  return days
})

const getCellClasses = (day) => ({
  '_other-month': !day.isCurrentMonth,
  '_cell-day': day.isCurrentMonth,
  _current: day.isToday,
  '_selected': selectedDate.value && day.date.isSame(selectedDate.value, 'day')
})

const selectedDateFormatted = computed(() =>
  selectedDate.value ? selectedDate.value.format('DD.MM.YY') : '—',
)

const currentMonthFormatted = computed(() => currentMonth.value.format('MMMM YYYY'))

const selectDate = (day) => {
  if (day.isCurrentMonth) {
    selectedDate.value = day.date
  }
}

const prevMonth = () => {
  currentMonth.value = currentMonth.value.subtract(1, 'month')
}

const nextMonth = () => {
  currentMonth.value = currentMonth.value.add(1, 'month')
}
const dateLabel = computed(() =>
  selectedDate.value ? 'Срок исполнения:' : 'Выберите срок исполнения',
)
</script>

<style lang="scss" scoped>
// Календарь

.calendar__cells {
  display: grid;
  grid-template-columns: repeat(7, 1fr);
}

.calendar__cell {
  text-align: center;
  cursor: pointer;

  transition: all 0.2s ease;
}

._other-month {
  opacity: 0.5;
}

._current {
  background: #fff3e0;
  font-weight: bold;
}

.date-control {
  font-weight: 600;
  margin-left: 5px;
}

@media (max-width: 768px) {
  .calendar__cell {
    padding: 8px;
    font-size: 13px;
  }

  .calendar__days-names {
    display: none;
  }

  .calendar__month {
    font-size: 16px;
  }

  .nav__action svg {
    width: 16px;
    height: 16px;
  }
}

@media (max-width: 480px) {
  .calendar__cell {
    padding: 4px;
    font-size: 12px;
    min-width: 24px;
  }

  .calendar__nav {
    flex-direction: column;
    gap: 8px;
  }

  .calendar__period {
    font-size: 14px;
  }
}
._selected {
  color: #000000;
  font-weight: bold;
}
</style>
